insert into public.services(slug,name,emoji,description,price,delivery,features,status,visibility) values
('free_demo','Free Demo','🆓','One small demo section so you can see the SRIJAN quality before choosing a larger package.',1,'Same day','["1 small demo section","Quick quality preview"]','published','public'),
('quick_start','Quick Start','🌱','1 small website section or simple edit.',99,'Same day','["1 small section","Basic responsive styling"]','published','public'),
('mini_web','Mini Web','⚡','1-page basic website.',499,'1 day','["1 page","Responsive layout","Basic deployment"]','published','public'),
('starter','Starter','🎯','1-page polished website.',1499,'1–2 days','["1 polished page","Responsive design","Basic contact CTA"]','published','public'),
('business','Business','🚀','Up to 3 pages + WhatsApp.',2999,'2–3 days','["Up to 3 pages","WhatsApp","Responsive design"]','published','public'),
('growth','Growth ⭐','💼','Up to 5 pages + forms + Maps.',4999,'3–5 days','["Up to 5 pages","Forms","Google Maps"]','published','public'),
('professional','Professional','💎','Up to 8 pages + premium UI + basic SEO.',7999,'5–7 days','["Up to 8 pages","Premium UI","Basic SEO"]','published','public'),
('ai_smart','AI Smart','🤖','Up to 10 pages + one practical AI feature.',10999,'7–10 days','["Up to 10 pages","AI feature","Responsive design"]','published','public'),
('premium','Premium','👑','Up to 12 pages + AI + integrations.',14999,'10–14 days','["Up to 12 pages","AI","Integrations"]','published','public')
on conflict (slug) do update set name=excluded.name,description=excluded.description,price=excluded.price,delivery=excluded.delivery,features=excluded.features;

insert into public.addons(slug,name,emoji,price,delivery) values
('extra_page','Extra Page','📄',499,'1 day'),('extra_images_3','3 Extra Images','🖼️',299,'Same day'),('extra_images_10','10 Extra Images','🖼️',599,'Same day–1 day'),('gallery','Gallery Section','📸',799,'1 day'),('premium_ui','Premium UI Section','🎨',999,'1 day'),('animation','Extra Animation','✨',499,'Same day–1 day'),('whatsapp','WhatsApp Integration','💬',499,'Same day'),('maps','Google Maps','📍',299,'Same day'),('click_call','Click-to-Call','📞',299,'Same day'),('enquiry_form','Enquiry Form','📩',999,'1–2 days'),('email_notification','Email Notification','📧',999,'1–2 days'),('seo','Basic SEO','🔍',1499,'1–2 days'),('mobile','Mobile Optimization','📱',999,'1 day'),('performance','Performance Optimization','⚡',999,'1–2 days'),('api','Basic API Integration','🔗',1499,'2–3 days'),('ai_faq','AI FAQ','🤖',1499,'1–2 days'),('ai_chatbot','AI Chatbot','🤖',2999,'2–4 days'),('ai_content','AI Content Setup','🧠',999,'1 day'),('python','Simple Python Automation','🐍',1499,'2–3 days'),('excel','Excel/CSV Automation','📊',999,'1–2 days'),('vercel','Vercel Deployment','🚀',699,'Same day'),('hosting','Domain/Hosting Setup','🌐',699,'Same day–1 day'),('revision','Extra Revision Round','🛠️',499,'1 day'),('maintenance','Monthly Maintenance','🔧',999,'Ongoing'),('emergency_support','Emergency WhatsApp Support','🚨',150,'Immediate')
on conflict (slug) do update set name=excluded.name,price=excluded.price,delivery=excluded.delivery;
